### PR TITLE
Fix versioning in modelDescription

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
In an OSMP modelDescription, there are 3 different version to set. None of them are set in the current master branch, as pointed out by https://github.com/esmini/esmini/issues/475.

In this PR 3 versions are set in the CMakeLists of the OSMP FMU:
- VERSION: Version of the FMU itself. We could set it to the same version number as esmini itself. @eknabe can we access this directly in the repository? the version.txt does not contain the actual version number.
- OSIVERSION: OSI version used by esmini. As already mentioned in the corresponding issue: @eknabe any idea on how to set this automatically?
- OSMPVERSION: Can be set manually, depending on which OSMP version is actually used, as implemented in this PR,

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
I currently hardcoded the version numbers for all three, just to show that it generally works. They should now all be contained in the modelDescription. @localhorst87 can you verify this?

@eknabe could you assist on setting the esmini version and the osi version automatically in the CMakeLists?

**Comment by ClemensLinnhoff** [comment]
I currently hardcoded the version numbers for all three, just to show that it generally works. They should now all be contained in the modelDescription. @localhorst87 can you verify this?

@eknabe could you assist on setting the esmini version and the osi version automatically in the CMakeLists?

**Comment by eknabevcc** [comment]
version.txt should contain tag. Example:

```
ESMINI_GIT_REV="e56d4c1"
ESMINI_GIT_TAG="v2.31.1"
ESMINI_GIT_BRANCH="tags/v2.31.1"
ESMINI_BUILD_VERSION="3246"
```
But if the current commit (HEAD) is not on a tag it will be empty.

Regarding OSI version, I'm not sure how to grab version nr easily. 

I'm preparing a release for today. I suggest we merge what you have and we can refine the versioning later. What do you think?

**Comment by ClemensLinnhoff** [comment]
> I'm preparing a release for today. I suggest we merge what you have and we can refine the versioning later. What do you think?

What will be the Release Tag? 2.32.1? Then I can put this already in the CMakeLists. And for this release it will match.

**Comment by ClemensLinnhoff** [comment]
And are you still on OSI 3.5 or will you update to 3.6?

**Comment by eknabevcc** [comment]
> And are you still on OSI 3.5 or will you update to 3.6?

Still [v3.5.0](https://github.com/esmini/esmini/blob/6c252273c5aa2422d5629a59febeee436fa74ee2/scripts/generate_osi_libs.sh#L31C1-L31C18)

**Comment by eknabevcc** [comment]
> > I'm preparing a release for today. I suggest we merge what you have and we can refine the versioning later. What do you think?
> 
> What will be the Release Tag? 2.32.1? Then I can put this already in the CMakeLists. And for this release it will match.

Ah, yes, release tag will be v2.32.1

**Comment by ClemensLinnhoff** [comment]
I changed to hardcoded versions. Now it fit to the next release and can be merged.

**Comment by eknabevcc** [comment]
I can add a dynamic version setting, however I can't edit files in this branch/repo. I'll do it after merge.

**Pull request merged**
